/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.text.Normalizer;
import javax.swing.JOptionPane;
import model.Livro;
import service.LivroService;
import service.ServiceFactory;

/**
 *
 * @author PICHAU
 */
public class AlterarLivro extends javax.swing.JInternalFrame {

    /**
     * Creates new form AlterarLivro
     */
    public AlterarLivro() {
        initComponents();
    }

    private static String formatString(String s) {
        String temp = Normalizer
                .normalize(s, Normalizer.Form.NFD)
                .replaceAll("[^\\p{ASCII}]", "");
        return s;
    }

    private Livro valida(long idIsbn) {

        Livro livro = null;
        String autoresTemp = autores.getText().trim();
        String isbnTemp = isbn.getText().trim();
        String semelhanteTemp = semelhantes.getText().trim();
        String dataTemp = dataPub.getText().trim();
        String tituloTemp = titulo.getText().trim();
        System.out.println(autores.getText().trim());

        if (autoresTemp.isEmpty()
                || isbnTemp.isEmpty()                
                || dataTemp.isEmpty()
                || tituloTemp.isEmpty()) {
            return livro;
        } else {

            autoresTemp = formatString(autoresTemp);
            isbnTemp = formatString(isbnTemp);
            semelhanteTemp = formatString(semelhanteTemp);
            dataTemp = formatString(dataTemp);
            tituloTemp = formatString(tituloTemp);

            livro = new Livro(idIsbn);
            livro.setAutores(autoresTemp);
            livro.setSemelhantes(semelhanteTemp);
            livro.setDataPublicacao(dataTemp);
            livro.setTitulo(tituloTemp);
            livro.setIsbn(isbnTemp);

        }

        return livro;
    }

    private void updateLivro() {
        LivroService entity = ServiceFactory.getLivroService();

        Long idIsbn = entity.recuperaIsbn(isbn.getText());

        Livro livro;
        livro = valida(idIsbn);
        if (livro != null) {
            long idPessoa = entity.verifica(Sistema.getUsuario());

            livro.setIdPessoa(idPessoa);

            if (entity.update(livro, idPessoa)) {
                JOptionPane.showMessageDialog(null, "Livro " + isbn.getText() + " ATUALIZADO");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "ERRO");

            }
        } else {
            JOptionPane.showMessageDialog(null, "Dados INVALIDOS - Tente Novamente");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label2 = new java.awt.Label();
        label1 = new java.awt.Label();
        isbn = new javax.swing.JLabel();
        nome = new java.awt.Label();
        label = new java.awt.Label();
        nome7 = new java.awt.Label();
        nome5 = new java.awt.Label();
        titulo = new java.awt.TextField();
        autores = new java.awt.TextField();
        dataPub = new javax.swing.JFormattedTextField();
        atualizarLivro = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        semelhantes = new javax.swing.JTextArea();

        label2.setText("label2");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Alterar Livro");

        label1.setText("ISBN");

        nome.setText("Título");

        label.setText("Autores");

        nome7.setText("Semelhantes");

        nome5.setText("Data da Publicação");

        dataPub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataPubActionPerformed(evt);
            }
        });

        atualizarLivro.setActionCommand("AtualizarLivro");
        atualizarLivro.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        atualizarLivro.setForeground(new java.awt.Color(0, 0, 255));
        atualizarLivro.setLabel("Atualizar");
        atualizarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarLivroActionPerformed(evt);
            }
        });

        semelhantes.setColumns(20);
        semelhantes.setRows(5);
        jScrollPane1.setViewportView(semelhantes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nome5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nome7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(atualizarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(isbn, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(dataPub, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                        .addComponent(titulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                        .addComponent(autores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isbn, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(autores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nome5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataPub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nome7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(atualizarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataPubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataPubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataPubActionPerformed

    private void atualizarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarLivroActionPerformed
        // TODO add your handling code here:
        updateLivro();

    }//GEN-LAST:event_atualizarLivroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button atualizarLivro;
    public java.awt.TextField autores;
    public javax.swing.JFormattedTextField dataPub;
    public javax.swing.JLabel isbn;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label nome;
    private java.awt.Label nome5;
    private java.awt.Label nome7;
    public javax.swing.JTextArea semelhantes;
    public java.awt.TextField titulo;
    // End of variables declaration//GEN-END:variables
}
