/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.List;
import service.ServiceFactory;
import javax.swing.JOptionPane;
import model.Classificacao;
import model.Livro;
import service.ClassificacaoService;
import service.LivroService;
import utils.validacao;


public class CadastroLivroManualmente extends javax.swing.JInternalFrame {

    public CadastroLivroManualmente() {
        ClassificacaoService entity = ServiceFactory.getClassificacaoService();
        List<Classificacao> nomes = entity.recuperaClassificacao();
        if (nomes.size() > 0) {
            initComponents();
        } else {
            JOptionPane.showMessageDialog(null, "Cadastre uma Categoria Primeiro");           
            this.dispose();
        }
    }

    public final void categorias() {
        ClassificacaoService entity = ServiceFactory.getClassificacaoService();

        List<Classificacao> nomes = entity.recuperaClassificacao();

        Classificacao nome;
        String[] dados = new String[nomes.size()];
        if (nomes.size() > 0) {
            for (int i = 0; i < nomes.size(); i++) {
                nome = nomes.get(i);
                dados[i] = nome.getNome();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Cadastre uma Categoria Primeiro");
            
            this.dispose();
        }

        classifica = new javax.swing.JComboBox<>();
        classifica.setModel(new javax.swing.DefaultComboBoxModel<>(dados));

    }

    private void cadLivro() {
        LivroService entity = ServiceFactory.getLivroService();
        String isbnTemp = validacao.formatString(isbn.getText());

        long idIsbn = entity.recuperaIsbn(isbnTemp);

        Livro livro;
        long idPessoa = entity.verifica(Sistema.getUsuario());

        String autoresTemp = autores.getText().trim();
        String semelhanteTemp = semelhante.getText().trim();
        String dataTemp = dataPub.getText().trim();
        String tituloTemp = titulo.getText().trim();
        String classTemp = (classifica.getSelectedItem()).toString();

        if (idIsbn == -1) {
            idIsbn = entity.recuperaUltimoId() + 1;
            livro = validacao.validaLivro(idIsbn, autoresTemp, isbnTemp,
                    semelhanteTemp, dataTemp, tituloTemp, classTemp);

            if (livro != null) {
                livro.setIdPessoa(idPessoa);
                entity.save(livro);
                JOptionPane.showMessageDialog(null, "Livro " + isbnTemp + " CADASTRADO");
            } else {
                JOptionPane.showMessageDialog(null, "Dados INVALIDOS - Tente Novamente");
            }
        } else {
            livro = validacao.validaLivro(idIsbn, autoresTemp, isbnTemp,
                    semelhanteTemp, dataTemp, tituloTemp, classTemp);
            if (livro != null) {
                livro.setIdPessoa(idPessoa);
                entity.update(livro, idPessoa);
                JOptionPane.showMessageDialog(null, "Livro " + isbnTemp + " já "
                        + "estava cadastrado e foi ATUALIZADO");
            } else {
                JOptionPane.showMessageDialog(null, "Dados INVALIDOS - Tente Novamente");
            }
        }
    }

    public static void mudaSemelhante(String isbnS, String tituloS,
            String dataS, String autor) {
        semelhante.setText(isbnS);
        titulo.setText(tituloS);
        dataPub.setText(dataS);
        autores.setText(autor);
    }

    private void selecionarSemelhante() {
        SelecionarSemelhante selecionar = new SelecionarSemelhante(this);
        getParent().add(selecionar);
        selecionar.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        titulo = new javax.swing.JTextField();
        isbn = new javax.swing.JTextField();
        autores = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        dataPub = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        classifica = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        semelhante = new javax.swing.JFormattedTextField();
        jButton5 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastrar Livro Manualmente");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Cadastro de Livro Manualmente");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setText("CADASTRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Título");

        jLabel9.setText("ISBN");

        jLabel10.setText("Data de Publicação");

        jLabel11.setText("Semelhante");

        jLabel12.setText("Autores");

        dataPub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataPubActionPerformed(evt);
            }
        });

        jLabel13.setText("Classificação");

        categorias();

        jButton4.setForeground(new java.awt.Color(204, 0, 51));
        jButton4.setText("-");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        semelhante.setEditable(false);
        semelhante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semelhanteActionPerformed(evt);
            }
        });

        jButton5.setText("+");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isbn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(titulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(autores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(dataPub, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(classifica, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(semelhante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)))))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataPub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(semelhante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5)
                        .addComponent(jButton4))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classifica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cadLivro();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void dataPubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataPubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataPubActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        semelhante.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void semelhanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semelhanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semelhanteActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        selecionarSemelhante();
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField autores;
    public javax.swing.JComboBox<String> classifica;
    public static javax.swing.JFormattedTextField dataPub;
    private javax.swing.JTextField isbn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JFormattedTextField semelhante;
    public static javax.swing.JTextField titulo;
    // End of variables declaration//GEN-END:variables
}
