/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JOptionPane;
import model.Contato;
import model.Endereco;
import service.ContatoService;
import service.EnderecoService;
import service.LivroService;
import service.LoginService;
import service.PessoaService;
import service.ServiceFactory;

/**
 *
 * @author PICHAU
 */
public class ExcluirUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form ExcluirClientes
     */
    public ExcluirUsuario() {
        initComponents();
    }

    private void excluirUsuario() {

        LivroService entity5 = ServiceFactory.getLivroService();
        PessoaService entity = ServiceFactory.getPessoaService();
        long idPessoa = entity.idCPF(cpf.getText());

        if (entity5.recuperaLivroPessoa(idPessoa).isEmpty()) {

            LoginService entity2 = ServiceFactory.getLoginService();
            EnderecoService entity3 = ServiceFactory.getEnderecoService();
            ContatoService entity4 = ServiceFactory.getContatoService();
            long login = entity2.consultaLongUsuario(idPessoa);

            Endereco endereco = entity3.recuperaEnderecoPessoa(idPessoa);
            
            if (login != -1) {
                entity2.exclui(login);
            }
            
            if (endereco != null) {
                entity3.exclui(endereco.getIdEndereco());
            }

            Contato contato = entity4.recuperaContatoPessoa(idPessoa);

            if (contato != null) {
                entity4.exclui(contato.getIdContato());
            }
            
            entity.exclui(idPessoa);
            
            JOptionPane.showMessageDialog(null, "Usuario Excluido");
        }else{
            JOptionPane.showMessageDialog(null, "Usuario cadastrou livro - Nao Pode Excluir");
        }
        
        this.dispose();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        cpf = new javax.swing.JLabel();
        Excluir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Excluir Usuario");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("Excluir Usuário");

        cpf.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N

        Excluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Excluir.setForeground(new java.awt.Color(204, 0, 51));
        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cpf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(69, 69, 69)
                .addComponent(Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        excluirUsuario();
    }//GEN-LAST:event_ExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Excluir;
    public javax.swing.JLabel cpf;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
