/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author PICHAU
 */
public class Sistema extends javax.swing.JFrame {

    public static String getUsuario() {
        return usuario;
    }

    public static void setUsuario(String aUsuario) {
        usuario = aUsuario;
    }

    public static String getSenha() {
        return senha;
    }

    public static void setSenha(String aSenha) {
        senha = aSenha;
    }

    public static int getAdmin() {
        return admin;
    }

    public static void setAdmin(int aAdmin) {
        admin = aAdmin;
    }

    private static String usuario;
    private static String senha;
    private static int admin;
    private static long idUsuario;

    /**
     * Creates new form Cadastro
     */
    public Sistema() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jddPrincipal = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        listaLivros = new javax.swing.JMenuItem();
        cliente = new javax.swing.JMenu();
        cadastrousuario = new javax.swing.JMenuItem();
        lista = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        javax.swing.GroupLayout jddPrincipalLayout = new javax.swing.GroupLayout(jddPrincipal);
        jddPrincipal.setLayout(jddPrincipalLayout);
        jddPrincipalLayout.setHorizontalGroup(
            jddPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jddPrincipalLayout.setVerticalGroup(
            jddPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        getContentPane().add(jddPrincipal);
        jddPrincipal.setBounds(0, 0, 1200, 560);

        jMenuBar2.setToolTipText("");
        jMenuBar2.setName(""); // NOI18N

        jMenu4.setText("Livros");

        jMenuItem2.setText("Cadastrar Livro Manualmente");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        listaLivros.setText("Lista de Livros");
        listaLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaLivrosActionPerformed(evt);
            }
        });
        jMenu4.add(listaLivros);

        jMenuBar2.add(jMenu4);

        cliente.setText("Usuários");

        cadastrousuario.setText("Cadastro");
        cadastrousuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrousuarioActionPerformed(evt);
            }
        });
        cliente.add(cadastrousuario);

        lista.setText("Lista de Usuario");
        lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaActionPerformed(evt);
            }
        });
        cliente.add(lista);

        jMenuBar2.add(cliente);

        setJMenuBar(jMenuBar2);

        setBounds(0, 0, 1228, 629);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrousuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrousuarioActionPerformed
        // TODO add your handling code here:
        CadastrarUsuario cad = new CadastrarUsuario();
        jddPrincipal.add(cad);
        cad.setVisible(true);


    }//GEN-LAST:event_cadastrousuarioActionPerformed

    private void listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaActionPerformed
        // TODO add your handling code here:
        ListaUsuario usu = new ListaUsuario();
        jddPrincipal.add(usu);
        usu.setVisible(true);

    }//GEN-LAST:event_listaActionPerformed

    private void listaLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaLivrosActionPerformed
        // TODO add your handling code here:

        ListaLivros lista = new ListaLivros();
        jddPrincipal.add(lista);
        lista.setVisible(true);

    }//GEN-LAST:event_listaLivrosActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        CadastroLivroManualmente cad = new CadastroLivroManualmente();
        jddPrincipal.add(cad);
        cad.setVisible(true);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                final JFrame frame = new JFrame("Login");

                JDialog login = new JDialogLogin(frame, true);

                login.setVisible(true);

                Sistema sistema = new Sistema();

                if (admin == 0) {
                    //sistema.administracao.setVisible(false);
                    sistema.cliente.setVisible(false);
                }

                sistema.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastrousuario;
    private javax.swing.JMenu cliente;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    public javax.swing.JDesktopPane jddPrincipal;
    private javax.swing.JMenuItem lista;
    private javax.swing.JMenuItem listaLivros;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the usuarioLogado
     */
}
